# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI/CD for MERN Stack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     working-directory: ./server/

    strategy:
      matrix:
        node-version: [ 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    
    - name: Checkout code
    - uses: actions/checkout@v3
    
    -name: Install dependencies
      run: npm run install-deps

    -name: Build Client
     working-directory: ./client
     run: npm run build

    -name: Build Server
     working-directory: ./server
     run: npm run build

     -name : Deploy Client
      working-directory: ./client
      run: |
       Deploy your React app (e.g., to Netlify, Vercel, etc.)
          # Example:
          # npm install -g netlify-cli
          # netlify deploy --prod

      - name: Deploy Server
        working-directory: ./server
        run: |
          # Deploy your Node.js server (e.g., to Heroku, AWS Elastic Beanstalk, etc.)
          # Example:
          # npm install -g heroku
          # heroku login
          # git push heroku main
    
     
    - run: npm ci
    - run: npm run build --if-present
    # - run: npm test
