# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI Workflow for React Client and Express Server

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install dependencies (Client)
        run: |
          cd client
          npm install
          cd ..

      - name: Build React App
        run: |
          cd client
          npm run build
          cd ..

      - name: Install dependencies (Server)
        run: |
          cd server
          npm install
          cd ..

      # - name: Test Server
      #   run: |
      #     cd server
      #     npm test
      #     cd ..

      # - name: Test Client
      #   run: |
      #     cd client
      #     npm test
      #     cd ..
